## Overriding values for Chart's values.yaml
## Example values to run Confluent Operator in Private Cloud
global:
  provider:
    name: azure
    #region: us-east
    region: us-west
    kubernetes:
       deployment:
         ## If kubernetes is deployed in multi zone mode then specify availability-zones as appropriate
         ## If kubernetes is deployed in single availability zone then specify appropriate values
         ## For the private cloud, use kubernetes node labels as appropriate
         zones:
          - '0'
          - '1'
          - '2'
    ##
    ## Docker registry endpoint where Confluent Images are available.
    ##
    registry:
      fqdn: docker.io
      credential:
        required: false
  sasl:
    plain:
      username: test
      password: test123
  authorization:
    rbac:
      enabled: false
    simple:
      enabled: false
    superUsers: []
  dependencies:
    mds:
      endpoint: ""
      publicKey: ""
  # initContainer:
  #   image:
  #     tag: 5.5.0.0-ubi8
##Operator
operator:
  image:
    tag: 0.364.0-ubi8
## Zookeeper cluster
##
zookeeper:
  name: zookeeper
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  jvmConfig:
    heapSize: 512M
  # image:
  #   tag: 5.5.0.0-ubi8
  disableHostPort: true

## Kafka Cluster
##
kafka:
  name: kafka
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  loadBalancer:
    enabled: true
    domain: "swoodemo.dev"
  tls:
    enabled: false
    fullchain: |-
    privkey: |-
    cacerts: |-
  metricReporter:
    enabled: true
  jvmConfig:
    heapSize: 512M
  # image:
  #   tag: 5.5.0.0-ubi8
  disableHostPort: true

## Connect Cluster
##
connect:
  name: connectors
  replicas: 2
  tls:
    enabled: false
    ## "" for none, "tls" for mutual auth
    authentication:
      type: ""
    fullchain: |-
    privkey: |-
    cacerts: |-
  loadBalancer:
    enabled: false
    domain: ""
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
      brokerCount: 3
    schemaRegistry:
      enabled: true
      url: http://schemaregistry:8081
  # image:
  #   tag: 5.5.0.0-ubi8
## Replicator Connect Cluster
##
replicator:
  name: replicator
  replicas: 1
  tls:
    enabled: false
    authentication:
      type: ""
    fullchain: |-
    privkey: |-
    cacerts: |-
  loadBalancer:
    enabled: false
    domain: ""
  dependencies:
    kafka:
      brokerCount: 3
      bootstrapEndpoint: kafka:9071
  # image:
  #   tag: 5.5.0.0-ubi8
##
## Schema Registry
##
schemaregistry:
  name: schemaregistry
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  jvmConfig:
    heapSize: 512M
  tls:
    enabled: false
    authentication:
      type: ""
    fullchain: |-
    privkey: |-
    cacerts: |-
  loadBalancer:
    enabled: false
    domain: ""
  dependencies:
    kafka:
      brokerCount: 3
      bootstrapEndpoint: kafka:9071
  # image:
  #   tag: 5.5.0.0-ubi8
##
## KSQL
##
ksql:
  name: ksql
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  jvmConfig:
    heapSize: 512M
  tls:
    enabled: false
    authentication:
      type: ""
    fullchain: |-
    privkey: |-
    cacerts: |-
  loadBalancer:
    enabled: true
    domain: "swoodemo.dev"
  dependencies:
    kafka:
      brokerCount: 3
      bootstrapEndpoint: kafka:9071
      brokerEndpoints: kafka-0.kafka:9071,kafka-1.kafka:9071,kafka-2.kafka:9071
    schemaRegistry:
      enabled: true
      tls:
        enabled: false
        authentication:
          type: ""
      url: http://schemaregistry:8081
  # image:
  #   tag: 5.5.0.0-ubi8

## Control Center (C3) Resource configuration
##
controlcenter:
  name: controlcenter
  license: ""
  ##
  ## C3 dependencies
  ##
  dependencies:
    c3KafkaCluster:
      brokerCount: 3
      bootstrapEndpoint: kafka:9071
      zookeeper:
        endpoint: zookeeper:2181
    connectCluster:
      enabled: true
      url: http://connectors:8083
    ksql:
      enabled: true
      url: http://ksql:9088
    schemaRegistry:
      enabled: true
      url: http://schemaregistry:8081
  ##
  ## C3 External Access
  ##
  loadBalancer:
    enabled: true
    domain: "swoodemo.dev"
  ##
  ## TLS configuration
  ##
  tls:
    enabled: false
    authentication:
      type: ""
    fullchain: |-
    privkey: |-
    cacerts: |-
  ##
  ## C3 authentication
  ##
  auth:
    basic:
      enabled: true
      ##
      ## map with key as user and value as password and role
      property:
        admin: Developer1,Administrators
        disallowed: no_access
  jvmConfig:
    heapSize: 2048M
  resources:
    requests:
      cpu: 200m
      memory: 2048Mi
  # image:
  #   tag: 5.5.0.0-ubi8
  disableHostPort: true
